version: "3"

services:
  course-registration-app-dh:
    container_name: course-registration-app-dh
    build: app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      - backend

  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=course_registration
      - MYSQL_USER=course_registration
      - MYSQL_PASSWORD=course_registration
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: notification_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    networks:
      - backend

networks:
  backend:

volumes:
  app:
  database:
